CREATE TABLE ALLOCATAIRES (
    NUMERO IDENTITY PRIMARY KEY,
    NO_AVS VARCHAR2(200) UNIQUE,
    PRENOM    VARCHAR2(200) NOT NULL,
    NOM    VARCHAR2(200) NOT NULL
);

CREATE TABLE ALLOCATIONS (
    NUMERO IDENTITY PRIMARY KEY,
    MONTANT NUMERIC(9,2) NOT NULL,
    CANTON VARCHAR2(2) NOT NULL,
    DEBUT DATE NOT NULL,
    FIN DATE
);

ALTER TABLE ALLOCATIONS ADD CONSTRAINT UK_ALLOCATIONS UNIQUE (CANTON,FIN);

CREATE TABLE ENFANTS (
    NUMERO IDENTITY PRIMARY KEY,
    NO_AVS VARCHAR2(200) UNIQUE,
    PRENOM    VARCHAR2(200) NOT NULL,
    NOM    VARCHAR2(200) NOT NULL
);

CREATE TABLE VERSEMENTS (
    NUMERO IDENTITY PRIMARY KEY NOT NULL,
    FK_ALLOCATAIRES NUMBER(20) NOT NULL,
    DATE_VERSEMENT    DATE NOT NULL,
    MOIS_VERSEMENT    DATE NOT NULL
);

ALTER TABLE VERSEMENTS ADD CONSTRAINT FK_VERSEMENTS1 FOREIGN KEY (FK_ALLOCATAIRES) REFERENCES ALLOCATAIRES(NUMERO);


CREATE TABLE ALLOCATIONS_ENFANTS (
     NUMERO IDENTITY PRIMARY KEY,
     FK_ENFANTS NUMBER(200) NOT NULL,
     FK_ALLOCATIONS    NUMBER(200) NOT NULL
);

ALTER TABLE ALLOCATIONS_ENFANTS ADD CONSTRAINT FK_ALLOCATIONS_ENFANTS1 FOREIGN KEY (FK_ENFANTS) REFERENCES ENFANTS(NUMERO);
ALTER TABLE ALLOCATIONS_ENFANTS ADD CONSTRAINT FK_ALLOCATIONS_ENFANTS2 FOREIGN KEY (FK_ALLOCATIONS) REFERENCES ALLOCATIONS(NUMERO);

CREATE TABLE VERSEMENTS_ALLOCATIONS (
    NUMERO IDENTITY PRIMARY KEY,
    FK_VERSEMENTS NUMBER(20) NOT NULL,
    FK_ALLOCATIONS_ENFANTS NUMBER(20) NOT NULL
);

ALTER TABLE VERSEMENTS_ALLOCATIONS ADD CONSTRAINT FK_VERSEMENTS_ALLOCATIONS1 FOREIGN KEY (FK_VERSEMENTS) REFERENCES VERSEMENTS(NUMERO);
ALTER TABLE VERSEMENTS_ALLOCATIONS ADD CONSTRAINT FK_VERSEMENTS_ALLOCATIONS2 FOREIGN KEY (FK_ALLOCATIONS_ENFANTS) REFERENCES ALLOCATIONS_ENFANTS(NUMERO);

CREATE TABLE ALLOCATIONS_NAISSANCE (
                                       NUMERO IDENTITY PRIMARY KEY,
                                       FK_ENFANTS NUMBER(200),
                                       MONTANT    NUMERIC(9,2)
);